LOAD DATA
TRUNCATE INTO TABLE CRS_LEGAL_CUSTOMER_TAX_INFO
FIELDS TERMINATED BY ' | '
TRAILING NULLCOLS
(
  CUSTOMER_ID,
  TAX_COUNTRY,
  TAX_TYPE,
  TAX_ID_NO,
  TAX_CFM_DATE,
  TAX_VALID_DATE,
  CERT_TYPE,
  NO_TAX_REASON,
  CREATE_DATE,
  CREATE_TIME,
  CREATE_TELLER_NO,
  LAST_UPDATE_DATE,
  LAST_UPDATE_TIME,
  LAST_UPDATE_TELLER_NO,
  LAST_OPTION_TYPE,
  LAST_UPDATE_JNL_NO,
  RESERVER1,
  RESERVER2,
  RESERVER3,
  RESERVER4,
  RESERVER5,
  REMARK
)
