LOAD DATA
TRUNCATE INTO TABLE CRS_LEGAL_CUSTOMER_CONTROLLER
FIELDS TERMINATED BY ' | '
TRAILING NULLCOLS
(
  CUSTOMER_ID,
  FRST_NAME,
  LST_NAME,
  BIRTH_DATE,
  ADDRESS_1,
  ADDRESS_2,
  ADDRESS_3,
  TAX_COUNTRY,
  TAX_ID_TYPE,
  TAX_ID_NO,
  NO_TAX_REASON,
  CREATE_DATE,
  CREATE_TIME,
  CREATE_TELLER_NO,
  LAST_UPDATE_DATE,
  LAST_UPDATE_TIME,
  LAST_UPDATE_TELLER_NO,
  LAST_OPTION_TYPE,
  LAST_UPDATE_JNL_NO,
  RESERVER1,
  RESERVER2,
  RESERVER3,
  RESERVER4,
  RESERVER5,
  REMARK
)
