
PROMPT DROP TABLE CRS_COUNTRY
DROP TABLE CRS_COUNTRY;

PROMPT CREATE TABLE CRS_COUNTRY
CREATE TABLE CRS_COUNTRY
(
  COUNTRY_NAME VARCHAR2(50),
  COUNTRY_ABBR VARCHAR2(2),
  CRSFLAG VARCHAR2(1),
  OP_USER VARCHAR2(20),
  OP_TIME VARCHAR2(8),
  OP_DATE VARCHAR2(8),
  RESERVER1 VARCHAR2(200),
  RESERVER2 VARCHAR2(200),
  RESERVER3 VARCHAR2(200),
  RESERVER4 VARCHAR2(200),
  RESERVER5 VARCHAR2(200)
);

COMMENT ON TABLE CRS_COUNTRY IS '国家表';


COMMENT ON COLUMN CRS_COUNTRY.COUNTRY_NAME IS '国家全称';
COMMENT ON COLUMN CRS_COUNTRY.COUNTRY_ABBR IS '国家简称';
COMMENT ON COLUMN CRS_COUNTRY.CRSFLAG IS 'CRS标识符(0:非Crs,1:Crs国家)';
COMMENT ON COLUMN CRS_COUNTRY.OP_USER IS '操作用户';
COMMENT ON COLUMN CRS_COUNTRY.OP_TIME IS '操作时间';
COMMENT ON COLUMN CRS_COUNTRY.OP_DATE IS '操作日期';
COMMENT ON COLUMN CRS_COUNTRY.RESERVER1 IS '预留字段一';
COMMENT ON COLUMN CRS_COUNTRY.RESERVER2 IS '预留字段二';
COMMENT ON COLUMN CRS_COUNTRY.RESERVER3 IS '预留字段三';
COMMENT ON COLUMN CRS_COUNTRY.RESERVER4 IS '预留字段四';
COMMENT ON COLUMN CRS_COUNTRY.RESERVER5 IS '预留字段五';






PROMPT DROP TABLE CRS_LEGAL_CUSTOMER
DROP TABLE CRS_LEGAL_CUSTOMER;

PROMPT CREATE TABLE CRS_LEGAL_CUSTOMER
CREATE TABLE CRS_LEGAL_CUSTOMER
(
  CUSTOMER_ID VARCHAR2(17),
  CUSTOMER_NAME VARCHAR2(600),
  OPEN_BRANCH VARCHAR2(5),
  COMPANY_TYPE VARCHAR2(2),
  SPE_FLAG VARCHAR2(1),
  CTL_FLAG VARCHAR2(1),
  CREATE_DATE VARCHAR2(8),
  CREATE_TIME VARCHAR2(6),
  CREATE_TELLER_NO VARCHAR2(7),
  LAST_UPDATE_DATE VARCHAR2(8),
  LAST_UPDATE_TIME VARCHAR2(6),
  LAST_UPDATE_TELLER_NO VARCHAR2(7),
  LAST_OPTION_TYPE VARCHAR2(1),
  LAST_UPDATE_JNL_NO VARCHAR2(8),
  RESERVER1 VARCHAR2(200),
  RESERVER2 VARCHAR2(200),
  RESERVER3 VARCHAR2(200),
  RESERVER4 VARCHAR2(200),
  RESERVER5 VARCHAR2(200),
  REMARK VARCHAR2(200)
);



COMMENT ON TABLE CRS_LEGAL_CUSTOMER IS '法人客户信息表';

COMMENT ON COLUMN CRS_LEGAL_CUSTOMER.CUSTOMER_ID IS '法人客户号';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER.CUSTOMER_NAME IS '法人公司名称';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER.OPEN_BRANCH IS '开户行';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER.COMPANY_TYPE IS '企业类型';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER.SPE_FLAG IS '特定法人标识';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER.CTL_FLAG IS '是否有控制人';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER.CREATE_DATE IS '经办日期';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER.CREATE_TIME IS '经办时间';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER.CREATE_TELLER_NO IS '经办柜员号';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER.LAST_UPDATE_DATE IS '最后修改日期';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER.LAST_UPDATE_TIME IS '最后修改时间';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER.LAST_UPDATE_TELLER_NO IS '最后修改柜员号';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER.LAST_OPTION_TYPE IS '最后一次操作类型 C-新增 U-修改 D-删除';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER.LAST_UPDATE_JNL_NO IS '最后修改的OIBS流水号';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER.RESERVER1 IS '预留字段一';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER.RESERVER2 IS '预留字段二';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER.RESERVER3 IS '预留字段三';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER.RESERVER4 IS '预留字段四';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER.RESERVER5 IS '预留字段五';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER.REMARK IS '备注信息';




PROMPT DROP TABLE CRS_LEGAL_CUSTOMER_CONTROLLER
DROP TABLE CRS_LEGAL_CUSTOMER_CONTROLLER;

PROMPT CREATE TABLE CRS_LEGAL_CUSTOMER_CONTROLLER
CREATE TABLE CRS_LEGAL_CUSTOMER_CONTROLLER
(
  CUSTOMER_ID VARCHAR2(17),
  FRST_NAME VARCHAR2(320),
  LST_NAME VARCHAR2(280),
  BIRTH_DATE VARCHAR2(8),
  ADDRESS_1 VARCHAR2(50),
  ADDRESS_2 VARCHAR2(50),
  ADDRESS_3 VARCHAR2(50),
  TAX_COUNTRY VARCHAR2(3),
  TAX_ID_TYPE VARCHAR2(10),
  TAX_ID_NO VARCHAR2(50),
  NO_TAX_REASON VARCHAR2(60),
  CREATE_DATE VARCHAR2(8),
  CREATE_TIME VARCHAR2(6),
  CREATE_TELLER_NO VARCHAR2(7),
  LAST_UPDATE_DATE VARCHAR2(8),
  LAST_UPDATE_TIME VARCHAR2(6),
  LAST_UPDATE_TELLER_NO VARCHAR2(7),
  LAST_OPTION_TYPE VARCHAR2(1),
  LAST_UPDATE_JNL_NO VARCHAR2(8),
  RESERVER1 VARCHAR2(200),
  RESERVER2 VARCHAR2(200),
  RESERVER3 VARCHAR2(200),
  RESERVER4 VARCHAR2(200),
  RESERVER5 VARCHAR2 (200),
  REMARK VARCHAR2 (200)
)
;

COMMENT ON TABLE CRS_LEGAL_CUSTOMER_CONTROLLER IS '法人客户控制人信息表';

COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_CONTROLLER.CUSTOMER_ID IS '法人客户号';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_CONTROLLER.FRST_NAME IS '控制人名字';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_CONTROLLER.LST_NAME IS '控制人姓';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_CONTROLLER.BIRTH_DATE IS '控制人出生日期';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_CONTROLLER.ADDRESS_1 IS '控制人地址第1行';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_CONTROLLER.ADDRESS_2 IS '控制人地址第2行';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_CONTROLLER.ADDRESS_3 IS '控制人地址第3行';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_CONTROLLER.TAX_COUNTRY IS '控制人税务国家';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_CONTROLLER.TAX_ID_TYPE IS '控制人税务类型';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_CONTROLLER.TAX_ID_NO IS '控制人税务号码';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_CONTROLLER.NO_TAX_REASON IS '没有税务识别号的原因';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_CONTROLLER.CREATE_DATE IS '经办日期';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_CONTROLLER.CREATE_TIME IS '经办时间';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_CONTROLLER.CREATE_TELLER_NO IS '经办柜员号';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_CONTROLLER.LAST_UPDATE_DATE IS '最后修改日期';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_CONTROLLER.LAST_UPDATE_TIME IS '最后修改时间';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_CONTROLLER.LAST_UPDATE_TELLER_NO IS '最后修改柜员号';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_CONTROLLER.LAST_OPTION_TYPE IS '最后一次操作类型 C-新增 U-修改 D-删除';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_CONTROLLER.LAST_UPDATE_JNL_NO IS '最后修改的OIBS流水号';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_CONTROLLER.RESERVER1 IS '预留字段一';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_CONTROLLER.RESERVER2 IS '预留字段二';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_CONTROLLER.RESERVER3 IS '预留字段三';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_CONTROLLER.RESERVER4 IS '预留字段四';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_CONTROLLER.RESERVER5 IS '预留字段五';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_CONTROLLER.REMARK IS '备注信息';





PROMPT DROP TABLE CRS_LEGAL_CUSTOMER_TAX_INFO
DROP TABLE CRS_LEGAL_CUSTOMER_TAX_INFO;

PROMPT CREATE TABLE CRS_LEGAL_CUSTOMER_TAX_INFO
CREATE TABLE CRS_LEGAL_CUSTOMER_TAX_INFO
(
  CUSTOMER_ID VARCHAR2(17),
  TAX_COUNTRY VARCHAR2(3),
  TAX_TYPE VARCHAR2(10),
  TAX_ID_NO VARCHAR2(50),
  TAX_CFM_DATE VARCHAR2(8),
  TAX_VALID_DATE VARCHAR2(8),
  CERT_TYPE VARCHAR2(10),
  NO_TAX_REASON VARCHAR2(60),
  CREATE_DATE VARCHAR2(8),
  CREATE_TIME VARCHAR2(6),
  CREATE_TELLER_NO VARCHAR2(7),
  LAST_UPDATE_DATE VARCHAR2(8),
  LAST_UPDATE_TIME VARCHAR2(6),
  LAST_UPDATE_TELLER_NO VARCHAR2(7),
  LAST_OPTION_TYPE VARCHAR2(1),
  LAST_UPDATE_JNL_NO VARCHAR2(8),
  RESERVER1 VARCHAR2(200),
  RESERVER2 VARCHAR2(200),
  RESERVER3 VARCHAR2(200),
  RESERVER4 VARCHAR2(200),
  RESERVER5 VARCHAR2(200),
  REMARK VARCHAR2(200)
);

COMMENT ON TABLE CRS_LEGAL_CUSTOMER_TAX_INFO IS '法人客户税务信息表';

COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_TAX_INFO.CUSTOMER_ID IS '法人客户号';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_TAX_INFO.TAX_COUNTRY IS '纳税地国/税号颁发国';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_TAX_INFO.TAX_TYPE IS '税务类型';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_TAX_INFO.TAX_ID_NO IS '税务识别号';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_TAX_INFO.TAX_CFM_DATE IS '税号确认时间';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_TAX_INFO.TAX_VALID_DATE IS '税号有效时间';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_TAX_INFO.CERT_TYPE IS '证明材料类型';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_TAX_INFO.NO_TAX_REASON IS '没有税务识别号的原因';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_TAX_INFO.CREATE_DATE IS '经办日期';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_TAX_INFO.CREATE_TIME IS '经办时间';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_TAX_INFO.CREATE_TELLER_NO IS '经办柜员号';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_TAX_INFO.LAST_UPDATE_DATE IS '最后修改日期';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_TAX_INFO.LAST_UPDATE_TIME IS '最后修改时间';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_TAX_INFO.LAST_UPDATE_TELLER_NO IS '最后修改柜员号';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_TAX_INFO.LAST_OPTION_TYPE IS '最后一次操作类型 C-新增 U-修改 D-删除';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_TAX_INFO.LAST_UPDATE_JNL_NO IS '最后修改的OIBS流水号';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_TAX_INFO.RESERVER1 IS '预留字段一';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_TAX_INFO.RESERVER2 IS '预留字段二';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_TAX_INFO.RESERVER3 IS '预留字段三';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_TAX_INFO.RESERVER4 IS '预留字段四';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_TAX_INFO.RESERVER5 IS '预留字段五';
COMMENT ON COLUMN CRS_LEGAL_CUSTOMER_TAX_INFO.REMARK IS '备注信息';










PROMPT DROP TABLE CRS_PERSONAL_CUSTOMER_TAX_INFO
DROP TABLE CRS_PERSONAL_CUSTOMER_TAX_INFO;

PROMPT CREATE TABLE CRS_PERSONAL_CUSTOMER_TAX_INFO
create table CRS_PERSONAL_CUSTOMER_TAX_INFO
(
  CUSTOMER_ID VARCHAR2(17),
  TAX_COUNTRY VARCHAR2(3),
  TAX_TYPE VARCHAR2(10),
  TAX_ID_NO VARCHAR2(50),
  TAX_CFM_DATE VARCHAR2(8),
  TAX_VALID_DATE VARCHAR2(8),
  CERT_TYPE VARCHAR2(10),
  NO_TAX_REASON VARCHAR2(60),
  CREATE_DATE VARCHAR2(8),
  CREATE_TIME VARCHAR2(6),
  CREATE_TELLER_NO VARCHAR2(7),
  LAST_UPDATE_DATE VARCHAR2(8),
  LAST_UPDATE_TIME VARCHAR2(6),
  LAST_UPDATE_TELLER_NO VARCHAR2(7),
  LAST_OPTION_TYPE VARCHAR2(1),
  LAST_UPDATE_JNL_NO VARCHAR2(8),
  RESERVER1 VARCHAR2(200),
  RESERVER2 VARCHAR2(200),
  RESERVER3 VARCHAR2(200),
  RESERVER4 VARCHAR2(200),
  RESERVER5 VARCHAR2(200),
  REMARK VARCHAR2(200)
)
;

COMMENT on table CRS_PERSONAL_CUSTOMER_TAX_INFO IS '个人客户税务信息表';

COMMENT on column CRS_PERSONAL_CUSTOMER_TAX_INFO.CUSTOMER_ID IS '个人客户账号';
COMMENT ON COLUMN CRS_PERSONAL_CUSTOMER_TAX_INFO.TAX_COUNTRY IS '纳税地国/税号颁发国';
COMMENT ON COLUMN CRS_PERSONAL_CUSTOMER_TAX_INFO.TAX_TYPE IS '税务类型';
COMMENT ON COLUMN CRS_PERSONAL_CUSTOMER_TAX_INFO.TAX_ID_NO IS '税务识别号';
COMMENT ON COLUMN CRS_PERSONAL_CUSTOMER_TAX_INFO.TAX_CFM_DATE IS '税号确认日期';
COMMENT ON COLUMN CRS_PERSONAL_CUSTOMER_TAX_INFO.TAX_VALID_DATE IS '税号有效日期';
COMMENT ON COLUMN CRS_PERSONAL_CUSTOMER_TAX_INFO.CERT_TYPE IS '证明材料类型';
COMMENT ON COLUMN CRS_PERSONAL_CUSTOMER_TAX_INFO.NO_TAX_REASON IS '没有税务识别号的原因';
COMMENT ON COLUMN CRS_PERSONAL_CUSTOMER_TAX_INFO.CREATE_DATE IS '经办日期';
COMMENT ON COLUMN CRS_PERSONAL_CUSTOMER_TAX_INFO.CREATE_TIME IS '经办时间';
COMMENT ON COLUMN CRS_PERSONAL_CUSTOMER_TAX_INFO.CREATE_TELLER_NO IS '经办柜员号';
COMMENT ON COLUMN CRS_PERSONAL_CUSTOMER_TAX_INFO.LAST_UPDATE_DATE IS '最后修改日期';
COMMENT ON COLUMN CRS_PERSONAL_CUSTOMER_TAX_INFO.LAST_UPDATE_TIME IS '最后修改时间';
COMMENT ON COLUMN CRS_PERSONAL_CUSTOMER_TAX_INFO.LAST_UPDATE_TELLER_NO IS '最后修改柜员号';
COMMENT ON COLUMN CRS_PERSONAL_CUSTOMER_TAX_INFO.LAST_OPTION_TYPE IS '最后一次操作类型 C-新增 U-修改 D-删除';
COMMENT ON COLUMN CRS_PERSONAL_CUSTOMER_TAX_INFO.LAST_UPDATE_JNL_NO IS '最后修改的OIBS流水号';
COMMENT ON COLUMN CRS_PERSONAL_CUSTOMER_TAX_INFO.RESERVER1 IS '预留字段一';
COMMENT ON COLUMN CRS_PERSONAL_CUSTOMER_TAX_INFO.RESERVER2 IS '预留字段二';
COMMENT ON COLUMN CRS_PERSONAL_CUSTOMER_TAX_INFO.RESERVER3 IS '预留字段三';
COMMENT ON COLUMN CRS_PERSONAL_CUSTOMER_TAX_INFO.RESERVER4 IS '预留字段四';
COMMENT ON COLUMN CRS_PERSONAL_CUSTOMER_TAX_INFO.RESERVER5 IS '预留字段五';
COMMENT ON COLUMN CRS_PERSONAL_CUSTOMER_TAX_INFO.REMARK IS '备注信息';
quit;
